version: '2'
services:
  financial-tracker-app:
    build: .
    environment:
      - NODE_ENV=PROD
      - FINANCIAL_TRACKER_SENDER_EMAIL_HOST=${FINANCIAL_TRACKER_SENDER_EMAIL_HOST}
      - FINANCIAL_TRACKER_SENDER_EMAIL_PORT=${FINANCIAL_TRACKER_SENDER_EMAIL_PORT}
      - FINANCIAL_TRACKER_SENDER_EMAIL_USER=${FINANCIAL_TRACKER_SENDER_EMAIL_USER}
      - FINANCIAL_TRACKER_SENDER_EMAIL_PASSWORD=${FINANCIAL_TRACKER_SENDER_EMAIL_PASSWORD}
      - FINANCIAL_TRACKER_RECEIVERS=${FINANCIAL_TRACKER_RECEIVERS}
    ports:
      - "${FINANCIAL_TRACKER_PORT}:80"
