version: '2'
services:
  financial-tracker-app:
    build: .
    depends_on:
      - financial-tracker-postgresql
    environment:
      - NODE_ENV=PROD
      - FINANCIAL_TRACKER_DATABASE_NAME=${FINANCIAL_TRACKER_DATABASE_NAME}
      - FINANCIAL_TRACKER_DATABASE_USER=${FINANCIAL_TRACKER_DATABASE_USER}
      - FINANCIAL_TRACKER_DATABASE_PASSWORD=${FINANCIAL_TRACKER_DATABASE_PASSWORD}
      - FINANCIAL_TRACKER_SENDER_EMAIL_HOST=${FINANCIAL_TRACKER_SENDER_EMAIL_HOST}
      - FINANCIAL_TRACKER_SENDER_EMAIL_PORT=${FINANCIAL_TRACKER_SENDER_EMAIL_PORT}
      - FINANCIAL_TRACKER_SENDER_EMAIL_USER=${FINANCIAL_TRACKER_SENDER_EMAIL_USER}
      - FINANCIAL_TRACKER_SENDER_EMAIL_PASSWORD=${FINANCIAL_TRACKER_SENDER_EMAIL_PASSWORD}
    ports:
      - "${FINANCIAL_TRACKER_PORT}:80"

  financial-tracker-postgresql:
    image: postgres:14.1
    volumes:
      - ~/.volumes/financial-tracker/postgresql/:/var/lib/postgresql/data/
      - ~/.volumes/financial-tracker/backups/:/opt/
    environment:
      - POSTGRES_USER=${FINANCIAL_TRACKER_DATABASE_USER}
      - POSTGRES_PASSWORD=${FINANCIAL_TRACKER_DATABASE_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
